return {
  -- add more treesitter parsers
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "awk",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "css",
        "cuda",
        "dockerfile",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "go",
        "help",
        "html",
        "htmldjango",
        "http",
        "ini",
        "java",
        "json",
        "javascript",
        "latex",
        "lua",
        "markdown",
        "markdown_inline",
        "matlab",
        "perl",
        "php",
        "python",
        "query",
        "r",
        "regex",
        "ruby",
        "scss",
        "sql",
        "swift",
        "typescript",
        "vim",
        "vue",
        "yaml",
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = "<nop>",
          node_decremental = "<bs>",
        },
      },
    },
  },
}
